#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  amixer -q sset Capture toggle
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  amixer -q sset Capture 10%-
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  amixer -q sset Capture 10%+
fi

statusLine=$(amixer get Capture | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  echo "<span color='#FF0000'> ${volume}%</span>"
  echo "${volume}%"
  echo ""
else
  echo " off"
  echo "off"
  echo ""
fi
