#!/bin/bash
# Based on https://aur.archlinux.org/packages/playerctl/

INSTANCE="${BLOCK_INSTANCE}"

if [[ "${INSTANCE}" != "" ]]; then
  ARGUMENTS="--player ${INSTANCE}"
  ps -e | grep "${INSTANCE}" &> /dev/null
fi
if [ $? == 1 ]; then
    exit 0
fi

ICON_PLAY=""
ICON_PAUSE=""
ICON_STOP=""
CUR_ICON=""

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
    $(playerctl ${ARGUMENTS} play-pause)
# elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
#     $(playerctl ${ARGUMENTS} play-pause)
# elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
#     $(playerctl ${ARGUMENTS} next)
fi

PLAYER_STATUS=$(playerctl ${ARGUMENTS} status)
INFO_TITLE=$(playerctl ${ARGUMENTS} metadata title)
INFO_ALBUM=$(playerctl ${ARGUMENTS} metadata album)
INFO_ARTIST=$(playerctl ${ARGUMENTS} metadata artist)

if [[ "${PLAYER_STATUS}" = "Paused" ]]; then
  CUR_ICON="${ICON_PAUSE}"
elif [[ "${PLAYER_STATUS}" = "Playing" ]]; then
  CUR_ICON="${ICON_PLAY}"
else
  CUR_ICON="${ICON_STOP}"
fi

INFO_TITLE=$(awk 'length > 30{$0 = substr($0, 1, 30) "..."} {printf "%-33s\n", $0}' <<< "$INFO_TITLE")
INFO_TITLE=$(echo $INFO_TITLE | xargs)

if [[ "${INFO_TITLE}" != "" ]] && [[ "${INFO_ARTIST}" != "" ]]; then
  echo "${CUR_ICON} ${INFO_TITLE}"
  echo " ${INFO_ARTIST} - ${INFO_TITLE} ${CUR_ICON}"
else
  echo " off"
fi